import {
  decisionsClause,
  vendorsClause,
  metricsClause,
  overridesClause,
  FINANCE_CITATION_INSTRUCTION,
  FINANCE_NARRATIVE_CONTRACT,
  outputAsDoc,
  type Template,
} from "./types";
import { registerFinanceTemplate } from "./registry";

const template: Template = {
  id: "finance:runway-analysis",
  label: "Runway analysis",
  hint: "Model how long the cash lasts and what changes it. Picks this for 'how much runway do we have', 'model the runway if we hire two engineers', 'when do we need to raise'.",
  kind: "doc",
  firstUseInputs: [
    {
      id: "cash",
      label: "Cash position",
      hint: "Cash in the bank today, and any committed inflows you're counting on. (e.g. '$1.4M, plus $200k SAFE closing in October')",
      required: true,
      kind: "text",
    },
    {
      id: "burn",
      label: "Burn",
      hint: "Current monthly burn, and the rough split (payroll vs everything else) if you know it.",
      required: true,
      kind: "text",
    },
    {
      id: "scenario",
      label: "Scenario to model",
      hint: "The change you want to test against the base case. (e.g. 'hire 2 engineers in Q1', 'cut paid spend to zero', 'revenue flat vs 10% MoM')",
      required: false,
      kind: "text",
    },
  ],
  buildPrompt({ task, brain, inputs, overrides }) {
    return [
      "You are modeling cash runway for a startup's founding team. The output is a decision tool, not a spreadsheet — it has to make the next move obvious.",
      decisionsClause(brain.recent_decisions),
      vendorsClause(brain.vendors),
      metricsClause(brain.metrics),
      "",
      FINANCE_NARRATIVE_CONTRACT,
      "",
      `Task: ${task}`,
      `Cash position: ${inputs.cash ?? "(unspecified)"}`,
      `Burn: ${inputs.burn ?? "(unspecified)"}`,
      inputs.scenario ? `Scenario to model: ${inputs.scenario}` : "",
      "",
      "Produce a runway analysis with this structure:",
      "  # Runway analysis",
      "  ",
      "  ## Headline",
      "  One or two sentences: months of runway in the base case, and the date that",
      "  implies. Then the single most important thing it forces.",
      "  ",
      "  ## Assumptions",
      "  Bullet every assumption the model rests on — cash, burn, the split, any inflow,",
      "  the growth rate. The reader checks the model by checking this list.",
      "  ",
      "  ## Base case",
      "  Walk the math. Cash / burn -> months. Show the arithmetic. Give the zero-cash date.",
      "  ",
      "  ## Scenarios",
      "  For the scenario the user named (and 1-2 obvious neighbors), a row: what changes,",
      "  the new monthly burn, the new runway, the new zero-cash date. Tag each burn change",
      "  as **[timing]** or **[structural]**.",
      "  ",
      "  ## Decision points",
      "  The dates, working backward: when to start a raise, when a hire becomes",
      "  unaffordable, when to cut. Be specific about the date and the trigger.",
      "  ",
      "  ## Recommendation",
      "  One clear call. What to do, and by when.",
      "  ",
      "  ## Open questions",
      "  Numbers you needed but didn't have.",
      "",
      "Constraints:",
      "- Never invent a number. Missing figure -> Open questions, and the model says",
      "  which results are blocked on it.",
      "- Show the arithmetic for every runway figure. No unexplained months-remaining.",
      "- A raise typically takes 3-6 months — the decision points must account for that.",
      "- Recommend one clear move. A runway analysis that ends in 'it depends' failed.",
      FINANCE_CITATION_INSTRUCTION,
      overridesClause(overrides ?? []),
      "",
      outputAsDoc("Runway Analysis"),
    ]
      .filter(Boolean)
      .join("\n");
  },
};

registerFinanceTemplate(template);
export default template;
