#!/usr/bin/env bash
# bootstrap-leaf.sh — scaffold a Distribution leaf and (re)generate its
# CLAUDE.md by prepending Main + Manager headers above the leaf's local body.
#
# Idempotent: re-running on an existing leaf regenerates only the
# auto-managed header section between the BEGIN/END markers.
#
# Usage:
#   bootstrap-leaf.sh <leaf-name>
#
# Effect:
#   - Creates bbc/distribution/<leaf-name>/ with local/, commands/, README.md,
#     and CLAUDE.md (copied from _template on first run).
#   - Inserts/refreshes a header block in CLAUDE.md containing Main + Manager
#     summaries, marked by:
#         <!-- BBC-AUTO-HEADER:BEGIN -->
#         ...
#         <!-- BBC-AUTO-HEADER:END -->

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ $# -lt 1 ]; then
  echo "Usage: bootstrap-leaf.sh <leaf-name>" >&2
  exit 2
fi

LEAF="$1"
LEAF_DIR="$ROOT/distribution/$LEAF"
TEMPLATE_DIR="$ROOT/distribution/_template"

# Validate leaf name (lowercase, kebab, no slashes)
case "$LEAF" in
  _template) echo "ERROR: cannot use reserved name '_template'" >&2; exit 2 ;;
  */*|*\\*|"") echo "ERROR: invalid leaf name: $LEAF" >&2; exit 2 ;;
esac

# First run: scaffold from template
if [ ! -d "$LEAF_DIR" ]; then
  echo "Scaffolding new leaf: $LEAF"
  mkdir -p "$LEAF_DIR/local" "$LEAF_DIR/commands"
  if [ -f "$TEMPLATE_DIR/CLAUDE.md" ]; then
    cp "$TEMPLATE_DIR/CLAUDE.md" "$LEAF_DIR/CLAUDE.md"
  else
    echo "ERROR: template CLAUDE.md not found at $TEMPLATE_DIR/CLAUDE.md" >&2
    exit 1
  fi
  cat > "$LEAF_DIR/README.md" <<EOF
# Leaf: $LEAF

Distribution leaf for BBC. See \`CLAUDE.md\` (regenerated by \`bootstrap-leaf.sh\`).

## Repo this leaf shadows

TODO: fill in the path of the actual repo this leaf governs (e.g.,
\`/Users/grid/Documents/GitHub/8azi-web/\`), or note "stub — no real repo yet".

## Local notes

\`local/\` contains pre-promotion notes — leaf-only knowledge. Promote up via
\`bash ../../scripts/propose.sh --target main ...\`.
EOF
fi

# Extract a section from a Markdown file, identified by its "## <heading>" line.
# Stops at the next line beginning with "## " (sibling heading) or end of file.
# Output includes the heading itself.
extract_section() {
  local file="$1"
  local heading="$2"
  awk -v h="## $heading" '
    $0 == h { collect=1; print; next }
    collect && /^## / { exit }
    collect { print }
  ' "$file"
}

MAIN_CLAUDE="$ROOT/CLAUDE.md"
PRECEDENCE_SECTION="$(extract_section "$MAIN_CLAUDE" "Precedence rule")"
PRINCIPLES_SECTION="$(extract_section "$MAIN_CLAUDE" "Non-negotiable principles")"

if [ -z "$PRECEDENCE_SECTION" ] || [ -z "$PRINCIPLES_SECTION" ]; then
  echo "ERROR: could not extract Precedence rule / Non-negotiable principles from $MAIN_CLAUDE" >&2
  echo "       (Main CLAUDE.md must have '## Precedence rule' and '## Non-negotiable principles' headings)" >&2
  exit 1
fi

# Generate the auto-header content. Main sections are verbatim; the Manager
# pointer is a brief instruction, since manager/CLAUDE.md is meant to be read
# by Manager-layer sessions, not inlined into leaves.
HEADER="$(cat <<HDR
<!-- BBC-AUTO-HEADER:BEGIN -->
> **Auto-generated by \`bootstrap-leaf.sh\`. Do not edit between the BEGIN/END markers.**
> The two sections below ("Precedence rule" and "Non-negotiable principles") are extracted **verbatim** from \`bbc/CLAUDE.md\`. They are NOT the entirety of Main — for the lock matrix, "What changes this file," and "What this file does NOT decide," read \`../../CLAUDE.md\` directly.
> Re-run \`bash ../../scripts/bootstrap-leaf.sh <this-leaf>\` to refresh after Main changes.

# Inherited from Main (\`bbc/CLAUDE.md\` — verbatim)

$PRECEDENCE_SECTION

$PRINCIPLES_SECTION

# How to act as a Distribution leaf

Read \`../../manager/CLAUDE.md\` for the review protocol. To propose any change to Main- or Manager-owned files, run from inside this leaf directory:

\`\`\`bash
bash ../../scripts/propose.sh \\
  --target <main|manager> \\
  --file <path-from-repo-root> \\
  --kind <edit|add|supersede> \\
  --summary "<short>" \\
  [--source "<who/what said so>"] \\
  [--body-file <path-with-diff-or-new-content>]
\`\`\`

Manager reviews via \`manager/agents/queue-reviewer.md\`. Approved proposals are applied by a human at Main running \`scripts/accept.sh\`.
<!-- BBC-AUTO-HEADER:END -->
HDR
)"

# Insert or replace the auto-header in CLAUDE.md
CLAUDE_MD="$LEAF_DIR/CLAUDE.md"
TMP="$(mktemp)"
HDR_TMP="$(mktemp)"
printf '%s\n' "$HEADER" > "$HDR_TMP"

if grep -q '<!-- BBC-AUTO-HEADER:BEGIN -->' "$CLAUDE_MD" 2>/dev/null; then
  # Replace existing block: print everything outside the markers, splice header at BEGIN.
  awk -v hdrfile="$HDR_TMP" '
    BEGIN {
      while ((getline line < hdrfile) > 0) {
        hdr = (hdr == "" ? line : hdr "\n" line)
      }
      close(hdrfile)
    }
    /<!-- BBC-AUTO-HEADER:BEGIN -->/ { print hdr; skip=1; next }
    /<!-- BBC-AUTO-HEADER:END -->/   { skip=0; next }
    !skip { print }
  ' "$CLAUDE_MD" > "$TMP"
  mv "$TMP" "$CLAUDE_MD"
else
  # Prepend block, preserving original content below.
  {
    cat "$HDR_TMP"
    echo
    cat "$CLAUDE_MD"
  } > "$TMP"
  mv "$TMP" "$CLAUDE_MD"
fi
rm -f "$HDR_TMP"

echo "Bootstrapped leaf: $LEAF"
echo "  CLAUDE.md:        $LEAF_DIR/CLAUDE.md (auto-header refreshed)"
echo "  local/:           $LEAF_DIR/local/"
echo "  commands/:        $LEAF_DIR/commands/"
echo "  README.md:        $LEAF_DIR/README.md"

# F3 log emission
bash "$ROOT/scripts/log-emit.sh" \
  --actor "human:main" \
  --action "bootstrap-leaf" \
  --target "distribution/$LEAF/CLAUDE.md" \
  >/dev/null 2>&1 || true
