#!/usr/bin/env bash
# index-memory.sh — regenerate memory/_index.md from frontmatter.
# Idempotent: same input → byte-identical output.
#
# Usage: bash scripts/index-memory.sh
# Run from repo root or any subdirectory.

set -euo pipefail

# Resolve repo root (script lives at <root>/scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MEM="$ROOT/memory"
OUT="$MEM/_index.md"

if [ ! -d "$MEM" ]; then
  echo "ERROR: memory/ not found at $MEM" >&2
  exit 1
fi

# Extract a single frontmatter field (between leading and trailing ---)
extract_field() {
  local file="$1"
  local field="$2"
  awk -v f="$field" '
    /^---$/ { in_fm = !in_fm; if (!in_fm) exit; next }
    in_fm {
      if ($0 ~ "^"f":") {
        sub("^"f":[[:space:]]*", "")
        gsub(/^"|"$/, "")
        print
        exit
      }
    }
  ' "$file"
}

{
  echo "# Memory Index"
  echo
  echo "_Auto-generated by \`scripts/index-memory.sh\`. Do not edit by hand._"
  echo

  # Find all .md files except _-prefixed meta files (e.g. _index.md, _schema.md,
  # _archive-index.md), sort deterministically. Convention: underscore prefix
  # means "directory-level meta/index, not a typed memory."
  files=$(find "$MEM" -type f -name '*.md' \
            ! -name '_*' \
            | LC_ALL=C sort)

  # Group by category (the directory directly under memory/)
  prev_cat=""
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    rel="${f#$MEM/}"
    cat="${rel%%/*}"
    if [ "$cat" != "$prev_cat" ]; then
      echo
      echo "## $cat"
      echo
      printf "| id | type | layer | scope | tags |\n"
      printf "|---|---|---|---|---|\n"
      prev_cat="$cat"
    fi
    id=$(extract_field "$f" id)
    type=$(extract_field "$f" type)
    layer=$(extract_field "$f" layer)
    scope=$(extract_field "$f" scope)
    tags=$(extract_field "$f" tags)
    # tags is a YAML inline list like [a, b]; render as-is
    printf "| \`%s\` | %s | %s | %s | %s |\n" \
      "$id" "$type" "$layer" "$scope" "$tags"
  done <<< "$files"
} > "$OUT"

echo "Wrote $OUT"
