#!/usr/bin/env bash
# index-archives.sh — generate memory/ops/_archive-index.md from
# memory/ops/providers/_archived/*.yaml.
#
# F4-build-3 finding #4: a future operator wondering "have we ever
# decommissioned X?" should be able to read one file. This is that file.
#
# Idempotent: same input → byte-identical output.
#
# Usage: bash scripts/index-archives.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ARCHIVED_DIR="$ROOT/memory/ops/providers/_archived"
OUT="$ROOT/memory/ops/_archive-index.md"

# Extract a single frontmatter field from a YAML file (top-of-file frontmatter).
extract_field() {
  local file="$1"
  local field="$2"
  awk -v f="$field" '
    /^---$/ { in_fm = !in_fm; if (!in_fm) exit; next }
    in_fm {
      if ($0 ~ "^"f":") {
        sub("^"f":[[:space:]]*", "")
        gsub(/^"|"$/, "")
        print
        exit
      }
    }
  ' "$file"
}

{
  echo "# Archive Index — Decommissioned Providers"
  echo
  echo "_Auto-generated by \`scripts/index-archives.sh\`. Do not edit by hand._"
  echo
  echo "Lists every provider adapter that has been moved to \`memory/ops/providers/_archived/\`. Active adapters are at \`memory/ops/providers/\`; current bindings are in \`memory/ops/bindings.yaml\`."
  echo

  if [ ! -d "$ARCHIVED_DIR" ]; then
    echo "_(No archived providers yet — \`memory/ops/providers/_archived/\` does not exist.)_"
  else
    files=$(find "$ARCHIVED_DIR" -maxdepth 1 -type f -name '*.yaml' | LC_ALL=C sort)
    if [ -z "$files" ]; then
      echo "_(No archived providers yet.)_"
    else
      printf "| provider_id | implements | archived_at | replacement | reason |\n"
      printf "|---|---|---|---|---|\n"
      while IFS= read -r f; do
        [ -z "$f" ] && continue
        pid=$(extract_field "$f" provider_id)
        impls=$(extract_field "$f" implements)
        archived_at=$(extract_field "$f" archived_at)
        # Fallback: if archived_at missing, use updated:
        [ -z "$archived_at" ] && archived_at=$(extract_field "$f" updated)
        replacement=$(extract_field "$f" replacement_provider_id)
        [ -z "$replacement" ] && replacement="—"
        reason=$(extract_field "$f" decommission_reason)
        [ -z "$reason" ] && reason="—"
        printf "| \`%s\` | %s | %s | %s | %s |\n" \
          "${pid:-?}" "${impls:-?}" "${archived_at:-?}" "$replacement" "$reason"
      done <<< "$files"
    fi
  fi

  echo
  echo "## See also"
  echo
  echo "- ADRs at \`memory/decisions/\` document each decommission's reason and lifecycle in long form."
  echo "- \`/bbc:decommission <provider>\` runs the Announce → Quarantine → Purge cycle."
} > "$OUT"

echo "Wrote $OUT"
